# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.prod:
        build:
            context: ./
            dockerfile: deploy/docker/app/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: smart-documentation-system/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '/storage/docker/app:/var/www/html/storage'
        networks:
            - laravel
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - '/storage/docker/database:/var/lib/mysql'
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    laravel:
        driver: bridge
